name: API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow
  # pull_request:
  #   branches: [ main ]

jobs:
  API-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm ci

      # Ensure the test-results directory exists 
      - name: Create test-results directory 
        run: mkdir -p test-results

      # Run API tests
      - name: Run API tests from the Tests/API folder
        run: npx playwright test Tests/API

      # Upload the test results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Check if the test-results directory has the report 
      - name: Check Test Results Directory 
        run: ls -l ./test-results

      # Test Reporter
      - name: Test Reporter 
        uses: dorny/test-reporter@v1 
        if: always() 
        with: 
          name: Test Results 
          path: ./test-results.xml 
          reporter: jest-junit
