name: API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow
  # pull_request:
  #   branches: [ main ]

jobs:
  API-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm ci

      # Run API tests
      - name: Run API tests from the Tests/API folder
        run: npx playwright test Tests/API

      # Upload the test results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-html-report
          path: html-report
          retention-days: 30

      # Include Summary Links
      - name: Add test result summary
        if: always()
        run: |
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- The detailed Playwright HTML report is available as an artifact." >> $GITHUB_STEP_SUMMARY

      # Log Key Information from the Report
      - name: Extract test summary
        run: |
          npx playwright show-report playwright-report --output=json > test-summary.json
          node extract-summary.js test-summary.json
