name: UI Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow
  # pull_request:
  #   branches: [ main ]

jobs:
  UI-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run UI tests from Tests/UI folder with xvfb-run 
        run: xvfb-run --auto-servernum -- npx playwright test Tests/UI
      
      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run tests
        run: npm test

      - name: Check Test Results Directory
        run: ls -l ./test-results

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: ./test-results/junit.xml
          reporter: jest-junit

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
